### ISSUE TITLE
"npm WARN deprecated pangyp@2.3.2: use node-gyp@3+, it does all the things"

### ISSUE THREAD

**Issue by karlek** [datasektionen/bawang#1]
Installerar bawang med `npm install`, den klagar och säger:
```
npm WARN deprecated pangyp@2.3.2: use node-gyp@3+, it does all the things
npm WARN prefer global pangyp@2.3.2 should be installed with -g
npm WARN prefer global bower@1.3.12 should be installed with -g

> node-sass@2.1.1 install /home/_/bawang/node_modules/node-sass
> node scripts/install.js

Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/linux-x64-node-4.1/binding.node

> node-sass@2.1.1 postinstall /home/_/bawang/node_modules/node-sass
> node scripts/build.js

module.js:338
    throw err;
    ^

Error: Cannot find module '/home/_/bawang/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
Build failed
npm WARN prefer global bower@1.3.12 should be installed with -g

> node-sass@2.1.1 install /home/_/bawang/node_modules/node-sass
> node scripts/install.js


> node-sass@2.1.1 postinstall /home/_/bawang/node_modules/node-sass
> node scripts/build.js

module.js:338
    throw err;
    ^

Error: Cannot find module '/home/_/bawang/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
Build failed
npm WARN prefer global pangyp@2.3.2 should be installed with -g
```

Något paket jag inte har? <3

Edit: Hjälper ju att läsa READMEn innan............ Tror inte det är något problem, körde bara kommandona i fel ordning >.<

**Comment by aronstrandberg** [comment]
lol
